const QuestionPaper = require('../models/QuestionPaper');

// Shape returned to all clients (admin + survey)
// Contains stable MongoDB _id values plus ordering info.
const sanitizePillars = (pillars) => {
  if (!Array.isArray(pillars)) return [];
  return pillars.map((pillar, pIndex) => ({
    _id: pillar._id,
    name: pillar.name,
    order: pillar.order ?? pIndex,
    sections: Array.isArray(pillar.sections)
      ? pillar.sections.map((section, sIndex) => ({
          _id: section._id,
          name: section.name,
          order: section.order ?? sIndex,
          questions: Array.isArray(section.questions)
            ? section.questions.map((q, qIndex) => ({
                _id: q._id,
                text: q.text,
                order: q.order ?? qIndex,
              }))
            : [],
        }))
      : [],
  }));
};

// Normalize admin payload (which only sends name/sections/questions.text)
// into the MongoDB schema shape. IDs are always generated by MongoDB,
// never taken from the client, and ordering is derived from array index.
const normalizeDraftInput = (pillars) => {
  if (!Array.isArray(pillars)) return [];
  return pillars.map((pillar, pIndex) => ({
    name: pillar.name,
    order: typeof pillar.order === 'number' ? pillar.order : pIndex,
    sections: Array.isArray(pillar.sections)
      ? pillar.sections.map((section, sIndex) => ({
          name: section.name,
          order: typeof section.order === 'number' ? section.order : sIndex,
          questions: Array.isArray(section.questions)
            ? section.questions.map((q, qIndex) => ({
                text: q.text,
                order: typeof q.order === 'number' ? q.order : qIndex,
              }))
            : [],
        }))
      : [],
  }));
};

exports.getDraft = async (req, res, next) => {
  try {
    const doc = await QuestionPaper.getOrCreateDefault();
    res.json({
      pillars: sanitizePillars(doc.draft?.pillars || []),
      updatedAt: doc.draft?.updatedAt,
    });
  } catch (err) {
    next(err);
  }
};

exports.updateDraft = async (req, res, next) => {
  try {
    const { pillars } = req.body || {};
    if (!Array.isArray(pillars)) {
      return res.status(400).json({ error: 'pillars must be an array' });
    }

    // Ensure the default document exists (atomic upsert).
    await QuestionPaper.getOrCreateDefault();

    // Use an atomic update instead of `doc.save()` to avoid Mongoose
    // VersionError when multiple draft updates happen close together.
    const now = new Date();
    const updatedDoc = await QuestionPaper.findOneAndUpdate(
      { key: 'default' },
      {
        $set: {
          'draft.pillars': normalizeDraftInput(pillars),
          'draft.updatedAt': now,
        },
      },
      { new: true, runValidators: true }
    );

    if (!updatedDoc) {
      return res.status(500).json({ error: 'Failed to update draft' });
    }

    res.json({
      pillars: sanitizePillars(updatedDoc.draft.pillars),
      updatedAt: updatedDoc.draft.updatedAt,
    });
  } catch (err) {
    next(err);
  }
};

exports.publish = async (req, res, next) => {
  try {
    const doc = await QuestionPaper.getOrCreateDefault();
    doc.published.pillars = sanitizePillars(doc.draft.pillars || []);
    doc.published.publishedAt = new Date();
    await doc.save();

    res.json({
      pillars: sanitizePillars(doc.published.pillars),
      publishedAt: doc.published.publishedAt,
    });
  } catch (err) {
    next(err);
  }
};

exports.getPublished = async (req, res, next) => {
  try {
    const doc = await QuestionPaper.getOrCreateDefault();
    res.json({
      pillars: sanitizePillars(doc.published?.pillars || []),
      publishedAt: doc.published?.publishedAt,
    });
  } catch (err) {
    next(err);
  }
};

